/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faces from "./faces";
export type { faces };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Diamond } from "./Diamond";
export type { InitDiamond } from "./InitDiamond";
