/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface InitDiamondInterface extends Interface {
  getFunction(
    nameOrSignature: "getInitializationStatus" | "init"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DiamondInitialized" | "Initialized"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getInitializationStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [AddressLike, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getInitializationStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
}

export namespace DiamondInitializedEvent {
  export type InputTuple = [owner: AddressLike, name: string, symbol: string];
  export type OutputTuple = [owner: string, name: string, symbol: string];
  export interface OutputObject {
    owner: string;
    name: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InitDiamond extends BaseContract {
  connect(runner?: ContractRunner | null): InitDiamond;
  waitForDeployment(): Promise<this>;

  interface: InitDiamondInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getInitializationStatus: TypedContractMethod<
    [],
    [[boolean, boolean] & { roles: boolean; token: boolean }],
    "view"
  >;

  init: TypedContractMethod<
    [owner: AddressLike, name: string, symbol: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getInitializationStatus"
  ): TypedContractMethod<
    [],
    [[boolean, boolean] & { roles: boolean; token: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<
    [owner: AddressLike, name: string, symbol: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DiamondInitialized"
  ): TypedContractEvent<
    DiamondInitializedEvent.InputTuple,
    DiamondInitializedEvent.OutputTuple,
    DiamondInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;

  filters: {
    "DiamondInitialized(address,string,string)": TypedContractEvent<
      DiamondInitializedEvent.InputTuple,
      DiamondInitializedEvent.OutputTuple,
      DiamondInitializedEvent.OutputObject
    >;
    DiamondInitialized: TypedContractEvent<
      DiamondInitializedEvent.InputTuple,
      DiamondInitializedEvent.OutputTuple,
      DiamondInitializedEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
  };
}
