/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ClaimTopicsFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addClaimTopic"
      | "getClaimTopics"
      | "removeClaimTopic"
      | "selectorsIntrospection"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClaimTopicAdded" | "ClaimTopicRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addClaimTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimTopics",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeClaimTopic",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "selectorsIntrospection",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimTopics",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeClaimTopic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "selectorsIntrospection",
    data: BytesLike
  ): Result;
}

export namespace ClaimTopicAddedEvent {
  export type InputTuple = [topic: BigNumberish];
  export type OutputTuple = [topic: bigint];
  export interface OutputObject {
    topic: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimTopicRemovedEvent {
  export type InputTuple = [topic: BigNumberish];
  export type OutputTuple = [topic: bigint];
  export interface OutputObject {
    topic: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClaimTopicsFacet extends BaseContract {
  connect(runner?: ContractRunner | null): ClaimTopicsFacet;
  waitForDeployment(): Promise<this>;

  interface: ClaimTopicsFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addClaimTopic: TypedContractMethod<
    [topic: BigNumberish],
    [void],
    "nonpayable"
  >;

  getClaimTopics: TypedContractMethod<[], [bigint[]], "view">;

  removeClaimTopic: TypedContractMethod<
    [topic: BigNumberish],
    [void],
    "nonpayable"
  >;

  selectorsIntrospection: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addClaimTopic"
  ): TypedContractMethod<[topic: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimTopics"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "removeClaimTopic"
  ): TypedContractMethod<[topic: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "selectorsIntrospection"
  ): TypedContractMethod<[], [string[]], "view">;

  getEvent(
    key: "ClaimTopicAdded"
  ): TypedContractEvent<
    ClaimTopicAddedEvent.InputTuple,
    ClaimTopicAddedEvent.OutputTuple,
    ClaimTopicAddedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimTopicRemoved"
  ): TypedContractEvent<
    ClaimTopicRemovedEvent.InputTuple,
    ClaimTopicRemovedEvent.OutputTuple,
    ClaimTopicRemovedEvent.OutputObject
  >;

  filters: {
    "ClaimTopicAdded(uint256)": TypedContractEvent<
      ClaimTopicAddedEvent.InputTuple,
      ClaimTopicAddedEvent.OutputTuple,
      ClaimTopicAddedEvent.OutputObject
    >;
    ClaimTopicAdded: TypedContractEvent<
      ClaimTopicAddedEvent.InputTuple,
      ClaimTopicAddedEvent.OutputTuple,
      ClaimTopicAddedEvent.OutputObject
    >;

    "ClaimTopicRemoved(uint256)": TypedContractEvent<
      ClaimTopicRemovedEvent.InputTuple,
      ClaimTopicRemovedEvent.OutputTuple,
      ClaimTopicRemovedEvent.OutputObject
    >;
    ClaimTopicRemoved: TypedContractEvent<
      ClaimTopicRemovedEvent.InputTuple,
      ClaimTopicRemovedEvent.OutputTuple,
      ClaimTopicRemovedEvent.OutputObject
    >;
  };
}
