/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../common";

export interface TrustedIssuersInternalFacetInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic: "TrustedIssuerAdded" | "TrustedIssuerRemoved"
  ): EventFragment;
}

export namespace TrustedIssuerAddedEvent {
  export type InputTuple = [issuer: AddressLike, claimTopics: BigNumberish[]];
  export type OutputTuple = [issuer: string, claimTopics: bigint[]];
  export interface OutputObject {
    issuer: string;
    claimTopics: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedIssuerRemovedEvent {
  export type InputTuple = [issuer: AddressLike];
  export type OutputTuple = [issuer: string];
  export interface OutputObject {
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustedIssuersInternalFacet extends BaseContract {
  connect(runner?: ContractRunner | null): TrustedIssuersInternalFacet;
  waitForDeployment(): Promise<this>;

  interface: TrustedIssuersInternalFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "TrustedIssuerAdded"
  ): TypedContractEvent<
    TrustedIssuerAddedEvent.InputTuple,
    TrustedIssuerAddedEvent.OutputTuple,
    TrustedIssuerAddedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedIssuerRemoved"
  ): TypedContractEvent<
    TrustedIssuerRemovedEvent.InputTuple,
    TrustedIssuerRemovedEvent.OutputTuple,
    TrustedIssuerRemovedEvent.OutputObject
  >;

  filters: {
    "TrustedIssuerAdded(address,uint256[])": TypedContractEvent<
      TrustedIssuerAddedEvent.InputTuple,
      TrustedIssuerAddedEvent.OutputTuple,
      TrustedIssuerAddedEvent.OutputObject
    >;
    TrustedIssuerAdded: TypedContractEvent<
      TrustedIssuerAddedEvent.InputTuple,
      TrustedIssuerAddedEvent.OutputTuple,
      TrustedIssuerAddedEvent.OutputObject
    >;

    "TrustedIssuerRemoved(address)": TypedContractEvent<
      TrustedIssuerRemovedEvent.InputTuple,
      TrustedIssuerRemovedEvent.OutputTuple,
      TrustedIssuerRemovedEvent.OutputObject
    >;
    TrustedIssuerRemoved: TypedContractEvent<
      TrustedIssuerRemovedEvent.InputTuple,
      TrustedIssuerRemovedEvent.OutputTuple,
      TrustedIssuerRemovedEvent.OutputObject
    >;
  };
}
