/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClaimTopicsEvents,
  IClaimTopicsEventsInterface,
} from "../../../../contracts/interfaces/events/IClaimTopicsEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicRemoved",
    type: "event",
  },
] as const;

export class IClaimTopicsEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IClaimTopicsEventsInterface {
    return new Interface(_abi) as IClaimTopicsEventsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClaimTopicsEvents {
    return new Contract(address, _abi, runner) as unknown as IClaimTopicsEvents;
  }
}
