/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRolesEvents,
  IRolesEventsInterface,
} from "../../../../contracts/interfaces/events/IRolesEvents";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "status",
        type: "bool",
      },
    ],
    name: "AgentSet",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
] as const;

export class IRolesEvents__factory {
  static readonly abi = _abi;
  static createInterface(): IRolesEventsInterface {
    return new Interface(_abi) as IRolesEventsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRolesEvents {
    return new Contract(address, _abi, runner) as unknown as IRolesEvents;
  }
}
