/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as errors from "./errors";
export type { errors };
import type * as events from "./events";
export type { events };
export type { IDiamondCut } from "./IDiamondCut";
export type { IEIP2535Introspection } from "./IEIP2535Introspection";
