/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ComplianceFacetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canTransfer"
      | "complianceRules"
      | "setMaxBalance"
      | "setMaxInvestors"
      | "setMinBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxBalanceSet"
      | "MaxInvestorsSet"
      | "MinBalanceSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "complianceRules",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxInvestors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinBalance",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "complianceRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinBalance",
    data: BytesLike
  ): Result;
}

export namespace MaxBalanceSetEvent {
  export type InputTuple = [max: BigNumberish];
  export type OutputTuple = [max: bigint];
  export interface OutputObject {
    max: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxInvestorsSetEvent {
  export type InputTuple = [max: BigNumberish];
  export type OutputTuple = [max: bigint];
  export interface OutputObject {
    max: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinBalanceSetEvent {
  export type InputTuple = [min: BigNumberish];
  export type OutputTuple = [min: bigint];
  export interface OutputObject {
    min: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ComplianceFacet extends BaseContract {
  connect(runner?: ContractRunner | null): ComplianceFacet;
  waitForDeployment(): Promise<this>;

  interface: ComplianceFacetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  complianceRules: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        maxBalance: bigint;
        minBalance: bigint;
        maxInvestors: bigint;
      }
    ],
    "view"
  >;

  setMaxBalance: TypedContractMethod<[max: BigNumberish], [void], "nonpayable">;

  setMaxInvestors: TypedContractMethod<
    [max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinBalance: TypedContractMethod<[min: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "complianceRules"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        maxBalance: bigint;
        minBalance: bigint;
        maxInvestors: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMaxBalance"
  ): TypedContractMethod<[max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxInvestors"
  ): TypedContractMethod<[max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinBalance"
  ): TypedContractMethod<[min: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "MaxBalanceSet"
  ): TypedContractEvent<
    MaxBalanceSetEvent.InputTuple,
    MaxBalanceSetEvent.OutputTuple,
    MaxBalanceSetEvent.OutputObject
  >;
  getEvent(
    key: "MaxInvestorsSet"
  ): TypedContractEvent<
    MaxInvestorsSetEvent.InputTuple,
    MaxInvestorsSetEvent.OutputTuple,
    MaxInvestorsSetEvent.OutputObject
  >;
  getEvent(
    key: "MinBalanceSet"
  ): TypedContractEvent<
    MinBalanceSetEvent.InputTuple,
    MinBalanceSetEvent.OutputTuple,
    MinBalanceSetEvent.OutputObject
  >;

  filters: {
    "MaxBalanceSet(uint256)": TypedContractEvent<
      MaxBalanceSetEvent.InputTuple,
      MaxBalanceSetEvent.OutputTuple,
      MaxBalanceSetEvent.OutputObject
    >;
    MaxBalanceSet: TypedContractEvent<
      MaxBalanceSetEvent.InputTuple,
      MaxBalanceSetEvent.OutputTuple,
      MaxBalanceSetEvent.OutputObject
    >;

    "MaxInvestorsSet(uint256)": TypedContractEvent<
      MaxInvestorsSetEvent.InputTuple,
      MaxInvestorsSetEvent.OutputTuple,
      MaxInvestorsSetEvent.OutputObject
    >;
    MaxInvestorsSet: TypedContractEvent<
      MaxInvestorsSetEvent.InputTuple,
      MaxInvestorsSetEvent.OutputTuple,
      MaxInvestorsSetEvent.OutputObject
    >;

    "MinBalanceSet(uint256)": TypedContractEvent<
      MinBalanceSetEvent.InputTuple,
      MinBalanceSetEvent.OutputTuple,
      MinBalanceSetEvent.OutputObject
    >;
    MinBalanceSet: TypedContractEvent<
      MinBalanceSetEvent.InputTuple,
      MinBalanceSetEvent.OutputTuple,
      MinBalanceSetEvent.OutputObject
    >;
  };
}
