/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as faces from "./faces";
export * as interfaces from "./interfaces";
export { Diamond__factory } from "./Diamond__factory";
export { InitDiamond__factory } from "./InitDiamond__factory";
