/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEIP2535Introspection,
  IEIP2535IntrospectionInterface,
} from "../../../contracts/interfaces/IEIP2535Introspection";

const _abi = [
  {
    inputs: [],
    name: "selectorsIntrospection",
    outputs: [
      {
        internalType: "bytes4[]",
        name: "selectors_",
        type: "bytes4[]",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class IEIP2535Introspection__factory {
  static readonly abi = _abi;
  static createInterface(): IEIP2535IntrospectionInterface {
    return new Interface(_abi) as IEIP2535IntrospectionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEIP2535Introspection {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IEIP2535Introspection;
  }
}
