/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDiamondCut__factory } from "./IDiamondCut__factory";
export { IEIP2535Introspection__factory } from "./IEIP2535Introspection__factory";
