/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClaimTopicsFacet__factory } from "./ClaimTopicsFacet__factory";
export { ComplianceFacet__factory } from "./ComplianceFacet__factory";
export { IdentityFacet__factory } from "./IdentityFacet__factory";
export { RolesFacet__factory } from "./RolesFacet__factory";
export { TokenFacet__factory } from "./TokenFacet__factory";
export { TrustedIssuersFacet__factory } from "./TrustedIssuersFacet__factory";
