/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BaseStorageAccessor__factory } from "./BaseStorageAccessor__factory";
export { ComplianceStorageAccessor__factory } from "./ComplianceStorageAccessor__factory";
export { MultiDomainStorageAccessor__factory } from "./MultiDomainStorageAccessor__factory";
export { RolesStorageAccessor__factory } from "./RolesStorageAccessor__factory";
export { TokenStorageAccessor__factory } from "./TokenStorageAccessor__factory";
