/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  MultiDomainStorageAccessor,
  MultiDomainStorageAccessorInterface,
} from "../../../contracts/abstracts/MultiDomainStorageAccessor";

const _abi = [
  {
    inputs: [],
    name: "getStorageNamespace",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getStorageStatus",
    outputs: [
      {
        internalType: "bool",
        name: "token",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "roles",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "compliance",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getStorageVersion",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class MultiDomainStorageAccessor__factory {
  static readonly abi = _abi;
  static createInterface(): MultiDomainStorageAccessorInterface {
    return new Interface(_abi) as MultiDomainStorageAccessorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MultiDomainStorageAccessor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MultiDomainStorageAccessor;
  }
}
