/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClaimTopicsErrors } from "./IClaimTopicsErrors";
export type { IComplianceErrors } from "./IComplianceErrors";
export type { IIdentityErrors } from "./IIdentityErrors";
export type { IRolesErrors } from "./IRolesErrors";
export type { ITokenErrors } from "./ITokenErrors";
export type { ITrustedIssuersErrors } from "./ITrustedIssuersErrors";
