/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseStorageAccessor } from "./BaseStorageAccessor";
export type { ComplianceStorageAccessor } from "./ComplianceStorageAccessor";
export type { MultiDomainStorageAccessor } from "./MultiDomainStorageAccessor";
export type { RolesStorageAccessor } from "./RolesStorageAccessor";
export type { TokenStorageAccessor } from "./TokenStorageAccessor";
