/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ClaimTopicsInternalFacet,
  ClaimTopicsInternalFacetInterface,
} from "../../../../contracts/facets/internal/ClaimTopicsInternalFacet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicRemoved",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea26469706673582212204f97c40c01c357568a3ba601b77fd7af690f49facd8cd53dfc257bb5eff3c07a64736f6c63430008110033";

type ClaimTopicsInternalFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClaimTopicsInternalFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ClaimTopicsInternalFacet__factory extends ContractFactory {
  constructor(...args: ClaimTopicsInternalFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ClaimTopicsInternalFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ClaimTopicsInternalFacet__factory {
    return super.connect(runner) as ClaimTopicsInternalFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClaimTopicsInternalFacetInterface {
    return new Interface(_abi) as ClaimTopicsInternalFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ClaimTopicsInternalFacet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ClaimTopicsInternalFacet;
  }
}
