/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  TrustedIssuersInternalFacet,
  TrustedIssuersInternalFacetInterface,
} from "../../../../contracts/facets/internal/TrustedIssuersInternalFacet";

const _abi = [
  {
    inputs: [],
    name: "EmptyClaimTopics",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
    ],
    name: "InvalidIssuer",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
    ],
    name: "TrustedIssuerAlreadyExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "issuer",
        type: "address",
      },
    ],
    name: "TrustedIssuerNotFound",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "Unauthorized",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "issuer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256[]",
        name: "claimTopics",
        type: "uint256[]",
      },
    ],
    name: "TrustedIssuerAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "issuer",
        type: "address",
      },
    ],
    name: "TrustedIssuerRemoved",
    type: "event",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220878b3da4461603d2397b41760d65dd80754e91cd93c73cef89d27ef3cf618abe64736f6c63430008110033";

type TrustedIssuersInternalFacetConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TrustedIssuersInternalFacetConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TrustedIssuersInternalFacet__factory extends ContractFactory {
  constructor(...args: TrustedIssuersInternalFacetConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TrustedIssuersInternalFacet & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TrustedIssuersInternalFacet__factory {
    return super.connect(runner) as TrustedIssuersInternalFacet__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TrustedIssuersInternalFacetInterface {
    return new Interface(_abi) as TrustedIssuersInternalFacetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TrustedIssuersInternalFacet {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TrustedIssuersInternalFacet;
  }
}
