/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClaimTopicsErrors,
  IClaimTopicsErrorsInterface,
} from "../../../../contracts/interfaces/errors/IClaimTopicsErrors";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicAlreadyExists",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicNotFound",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "topic",
        type: "uint256",
      },
    ],
    name: "InvalidClaimTopic",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "Unauthorized",
    type: "error",
  },
] as const;

export class IClaimTopicsErrors__factory {
  static readonly abi = _abi;
  static createInterface(): IClaimTopicsErrorsInterface {
    return new Interface(_abi) as IClaimTopicsErrorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClaimTopicsErrors {
    return new Contract(address, _abi, runner) as unknown as IClaimTopicsErrors;
  }
}
