/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IClaimIssuer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IClaimIssuer__factory>;
    getContractFactory(
      name: "IERC734",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC734__factory>;
    getContractFactory(
      name: "IERC735",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC735__factory>;
    getContractFactory(
      name: "IIdentity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentity__factory>;
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "Diamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Diamond__factory>;
    getContractFactory(
      name: "ClaimTopicsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ClaimTopicsFacet__factory>;
    getContractFactory(
      name: "ClaimTopicsFacetExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ClaimTopicsFacetExternal__factory>;
    getContractFactory(
      name: "ComplianceFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComplianceFacet__factory>;
    getContractFactory(
      name: "ComplianceFacetExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComplianceFacetExternal__factory>;
    getContractFactory(
      name: "DiamondCutFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondCutFacet__factory>;
    getContractFactory(
      name: "IdentityFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityFacet__factory>;
    getContractFactory(
      name: "IdentityFacetExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityFacetExternal__factory>;
    getContractFactory(
      name: "ClaimTopicsInternalFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ClaimTopicsInternalFacet__factory>;
    getContractFactory(
      name: "ComplianceInternalFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ComplianceInternalFacet__factory>;
    getContractFactory(
      name: "IdentityInternalFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IdentityInternalFacet__factory>;
    getContractFactory(
      name: "RolesInternalFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RolesInternalFacet__factory>;
    getContractFactory(
      name: "TokenInternalFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenInternalFacet__factory>;
    getContractFactory(
      name: "TrustedIssuersInternalFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustedIssuersInternalFacet__factory>;
    getContractFactory(
      name: "RolesFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RolesFacet__factory>;
    getContractFactory(
      name: "RolesFacetExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.RolesFacetExternal__factory>;
    getContractFactory(
      name: "TokenFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenFacet__factory>;
    getContractFactory(
      name: "TokenFacetExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenFacetExternal__factory>;
    getContractFactory(
      name: "TrustedIssuersFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustedIssuersFacet__factory>;
    getContractFactory(
      name: "TrustedIssuersFacetExternal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TrustedIssuersFacetExternal__factory>;
    getContractFactory(
      name: "InitDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitDiamond__factory>;
    getContractFactory(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractFactory(
      name: "IEIP2535Introspection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEIP2535Introspection__factory>;

    getContractAt(
      name: "IClaimIssuer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IClaimIssuer>;
    getContractAt(
      name: "IERC734",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC734>;
    getContractAt(
      name: "IERC735",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC735>;
    getContractAt(
      name: "IIdentity",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentity>;
    getContractAt(
      name: "Initializable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "Diamond",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Diamond>;
    getContractAt(
      name: "ClaimTopicsFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ClaimTopicsFacet>;
    getContractAt(
      name: "ClaimTopicsFacetExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ClaimTopicsFacetExternal>;
    getContractAt(
      name: "ComplianceFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ComplianceFacet>;
    getContractAt(
      name: "ComplianceFacetExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ComplianceFacetExternal>;
    getContractAt(
      name: "DiamondCutFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondCutFacet>;
    getContractAt(
      name: "IdentityFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityFacet>;
    getContractAt(
      name: "IdentityFacetExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityFacetExternal>;
    getContractAt(
      name: "ClaimTopicsInternalFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ClaimTopicsInternalFacet>;
    getContractAt(
      name: "ComplianceInternalFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ComplianceInternalFacet>;
    getContractAt(
      name: "IdentityInternalFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IdentityInternalFacet>;
    getContractAt(
      name: "RolesInternalFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RolesInternalFacet>;
    getContractAt(
      name: "TokenInternalFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenInternalFacet>;
    getContractAt(
      name: "TrustedIssuersInternalFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustedIssuersInternalFacet>;
    getContractAt(
      name: "RolesFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RolesFacet>;
    getContractAt(
      name: "RolesFacetExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.RolesFacetExternal>;
    getContractAt(
      name: "TokenFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenFacet>;
    getContractAt(
      name: "TokenFacetExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenFacetExternal>;
    getContractAt(
      name: "TrustedIssuersFacet",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustedIssuersFacet>;
    getContractAt(
      name: "TrustedIssuersFacetExternal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TrustedIssuersFacetExternal>;
    getContractAt(
      name: "InitDiamond",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InitDiamond>;
    getContractAt(
      name: "IDiamondCut",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondCut>;
    getContractAt(
      name: "IEIP2535Introspection",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEIP2535Introspection>;

    deployContract(
      name: "IClaimIssuer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimIssuer>;
    deployContract(
      name: "IERC734",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC734>;
    deployContract(
      name: "IERC735",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC735>;
    deployContract(
      name: "IIdentity",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentity>;
    deployContract(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Diamond",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Diamond>;
    deployContract(
      name: "ClaimTopicsFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimTopicsFacet>;
    deployContract(
      name: "ClaimTopicsFacetExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimTopicsFacetExternal>;
    deployContract(
      name: "ComplianceFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceFacet>;
    deployContract(
      name: "ComplianceFacetExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceFacetExternal>;
    deployContract(
      name: "DiamondCutFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DiamondCutFacet>;
    deployContract(
      name: "IdentityFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityFacet>;
    deployContract(
      name: "IdentityFacetExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityFacetExternal>;
    deployContract(
      name: "ClaimTopicsInternalFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimTopicsInternalFacet>;
    deployContract(
      name: "ComplianceInternalFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceInternalFacet>;
    deployContract(
      name: "IdentityInternalFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityInternalFacet>;
    deployContract(
      name: "RolesInternalFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RolesInternalFacet>;
    deployContract(
      name: "TokenInternalFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenInternalFacet>;
    deployContract(
      name: "TrustedIssuersInternalFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedIssuersInternalFacet>;
    deployContract(
      name: "RolesFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RolesFacet>;
    deployContract(
      name: "RolesFacetExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RolesFacetExternal>;
    deployContract(
      name: "TokenFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenFacet>;
    deployContract(
      name: "TokenFacetExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenFacetExternal>;
    deployContract(
      name: "TrustedIssuersFacet",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedIssuersFacet>;
    deployContract(
      name: "TrustedIssuersFacetExternal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedIssuersFacetExternal>;
    deployContract(
      name: "InitDiamond",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InitDiamond>;
    deployContract(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondCut>;
    deployContract(
      name: "IEIP2535Introspection",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEIP2535Introspection>;

    deployContract(
      name: "IClaimIssuer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimIssuer>;
    deployContract(
      name: "IERC734",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC734>;
    deployContract(
      name: "IERC735",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC735>;
    deployContract(
      name: "IIdentity",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentity>;
    deployContract(
      name: "Initializable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Initializable>;
    deployContract(
      name: "Diamond",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Diamond>;
    deployContract(
      name: "ClaimTopicsFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimTopicsFacet>;
    deployContract(
      name: "ClaimTopicsFacetExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimTopicsFacetExternal>;
    deployContract(
      name: "ComplianceFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceFacet>;
    deployContract(
      name: "ComplianceFacetExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceFacetExternal>;
    deployContract(
      name: "DiamondCutFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DiamondCutFacet>;
    deployContract(
      name: "IdentityFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityFacet>;
    deployContract(
      name: "IdentityFacetExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityFacetExternal>;
    deployContract(
      name: "ClaimTopicsInternalFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ClaimTopicsInternalFacet>;
    deployContract(
      name: "ComplianceInternalFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ComplianceInternalFacet>;
    deployContract(
      name: "IdentityInternalFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IdentityInternalFacet>;
    deployContract(
      name: "RolesInternalFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RolesInternalFacet>;
    deployContract(
      name: "TokenInternalFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenInternalFacet>;
    deployContract(
      name: "TrustedIssuersInternalFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedIssuersInternalFacet>;
    deployContract(
      name: "RolesFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RolesFacet>;
    deployContract(
      name: "RolesFacetExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.RolesFacetExternal>;
    deployContract(
      name: "TokenFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenFacet>;
    deployContract(
      name: "TokenFacetExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TokenFacetExternal>;
    deployContract(
      name: "TrustedIssuersFacet",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedIssuersFacet>;
    deployContract(
      name: "TrustedIssuersFacetExternal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TrustedIssuersFacetExternal>;
    deployContract(
      name: "InitDiamond",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InitDiamond>;
    deployContract(
      name: "IDiamondCut",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDiamondCut>;
    deployContract(
      name: "IEIP2535Introspection",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEIP2535Introspection>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
